// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from './routes/_app.tsx';
import * as $index from './routes/index.tsx';
import * as $queue_index from './routes/queue/index.tsx';
import * as $entriesManagement from './islands/entriesManagement.tsx';
import * as $entryManagement from './islands/entryManagement.tsx';
import * as $queueManagement from './islands/queueManagement.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_app.tsx': $_app,
    './routes/index.tsx': $index,
    './routes/queue/index.tsx': $queue_index,
  },
  islands: {
    './islands/entriesManagement.tsx': $entriesManagement,
    './islands/entryManagement.tsx': $entryManagement,
    './islands/queueManagement.tsx': $queueManagement,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
